# Use the Node.js image
FROM node:18-slim

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of your project
COPY . .

# Expose the port your app runs on
EXPOSE 5000

# Run the application
CMD ["npm", "start"]
